# coding: utf-8

# flake8: noqa
"""
    Pokémon API

    A simple API to fetch Pokémon data  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.inline_response200 import InlineResponse200
from swagger_client.models.inline_response404 import InlineResponse404
